name: Actions Ecosystem Create Comment - Extended
description: Create a comment to an issue or a pull request.
author: The Actions Ecosystem Authors
inputs:
  github_token:
    description: A GitHub token.
    required: true
  body:
    description: The comment body.
    required: true
  repo:
    description: The owner and repository name. e.g.) Codertocat/Hello-World
    required: false
    default: ${{ github.repository }}
  number:
    description: The number of the issue or pull request.
    required: false
  comment_uid:
    description: |
      A comment id to assign this comment with. Useful to create a single comment and 
      update it whenever the action runs.
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  icon: message-circle
  color: gray-dark
